config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: {in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="m-3">
  <h1>Restaurant List</h1>
  <p><%= link_to "Add a new Restaurant", new_restaurant_path %></p>
  <% @restaurants.each do |restaurant| %>
    <p><%=link_to restaurant.name, restaurant_path(restaurant)%></p>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>This is the new page</h1>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', restaurants_path %> |

app/views/restaurants/show.html.erb
<div class="m-3">
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.category.capitalize %></p>

  <% @restaurant.reviews.each do |review| %>
    <p><% review.rating.times do %>
      ⭐
    <% end %>
    | "<%= review.content %>"</p>
  <% end %>

 <p><%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %> <br>
  <%= link_to 'Back', restaurants_path %>
 </p>
</div>

app/views/reviews/new.html.erb
<div class="m-2">
  <h1> new review</h1>
  <%= simple_form_for([@restaurant, @review]) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit %>
  <% end %>

  <%= link_to 'Back', restaurants_path %> |
</div>